[run]
  timeout = "10m"
  skip-files = []
  skip-dirs = [ ]

[linters]
  disable-all = true
  enable = [
"asciicheck",
"bodyclose",
"cyclop",
"deadcode",
"depguard",
"dogsled",
"dupl",
"durationcheck",
"errcheck",
"errorlint",
"exhaustive",
"exhaustivestruct",
"exportloopref",
"forbidigo",
"forcetypeassert",
"funlen",
"gci",
"gochecknoglobals",
"gochecknoinits",
"gocognit",
"goconst",
"gocritic",
"gocyclo",
"godot",
"godox",
"goerr113",
"gofmt",
"gofumpt",
"goheader",
"goimports",
"golint",
"gomnd",
"gomoddirectives",
"gomodguard",
"goprintffuncname",
"gosec",
"gosimple",
"govet",
"ifshort",
"importas",
"ineffassign",
"interfacer",
"lll",
"makezero",
"maligned",
"misspell",
"nakedret",
"nestif",
"nilerr",
"nlreturn",
"noctx",
"nolintlint",
"paralleltest",
"prealloc",
"predeclared",
"promlinter",
"revive",
"rowserrcheck",
"scopelint",
"sqlclosecheck",
"staticcheck",
"structcheck",
"stylecheck",
"tagliatelle",
"testpackage",
"thelper",
"tparallel",
"typecheck",
"unconvert",
"unparam",
"unused",
"varcheck",
"wastedassign",
"whitespace",
"wrapcheck",
"wsl",
]