version: '3.3'
services:
  api:
    container_name: 'api'
    build: './'
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'
    environment:
      - APP_MONGO_DBURL=mongodb://mongo:27017
      - APP_PORT=8080
    entrypoint:
      - "make"
      - "run"

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
